# Generated by Django 5.1 on 2024-08-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cardholder_age_alter_metrocard_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrocard',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cardholder'),
        ),
    ]
